CC = g++
LFLAGS = -O3 -std=c++11
RFLAGS = 

symtrieigBisection.out: symtrieigBisection.cpp
	$(CC) $(LFLAGS) -o symtrieigBisection.out symtrieigBisection.cpp $(RFLAGS)

run: symtrieigBisection.out
	./symtrieigBisection.out

clear: 
	rm *.o *.out
